#! /bin/sh

set +u

# shellcheck disable=SC1091
#[ ! -s /lib/rc/sh/functions.sh ] || . /lib/rc/sh/functions.sh
[ ! -s /lib/gentoo/functions.sh ] || . /lib/gentoo/functions.sh

# OpenRC isn't ready for this... :(
#set -u

regenerateconfig() {
	basedir=''
	found=0

	for basedir in /var/state/bind /var/lib/bind /var/bind; do
		if [ -d "${basedir}"/pri/internal ] &&
				[ -x "${basedir}"/pri/internal/generate-ptr.sh ]
		then
			found=1
			(
				rc=0

				set +e

				cd "${basedir}"/pri/internal || return 1

				ebegin "Regenerating reverse mappings for internal zones"

				mkdir -p backup
				"${basedir}"/pri/internal/generate-ptr.sh ||
					rc=${?}
				mv -- *-20????????.zone backup/ 2>/dev/null

				eend ${rc} "Reverse map generation failed: ${rc}"
			) && break
		fi
	done

	if [ $(( found )) -eq 0 ]; then
		ewarn "Not regenerating internal zones"
	fi
} # regenerateconfig

regenerateconfig || exit ${?}

set -u

# vi: set sw=4 ts=4 syntax=sh:
