#! /bin/sh

set +u

# shellcheck disable=SC1091
#[ ! -s /lib/rc/sh/functions.sh ] || . /lib/rc/sh/functions.sh
[ ! -s /lib/gentoo/functions.sh ] || . /lib/gentoo/functions.sh

# OpenRC isn't ready for this... :(
#set -u

regenerateconfig() {
	rc=0

	# FIXME: Remove hard-coding of zone file name...
	if \
		[ -d /var/bind/pri/internal ] &&
		[ -x /var/bind/pri/internal/generate-ptr.sh ] &&
		[ -s /var/bind/pri/internal/miltonroad.net.zone ]
	then
		(
			set +e

			cd /var/bind/pri/internal || return 1

			ebegin "Regenerating reverse mappings for internal zones"

			mkdir -p backup
			/var/bind/pri/internal/generate-ptr.sh \
					/var/bind/pri/internal/miltonroad.net.zone ||
				rc=${?}
			mv -- ./*-20????????.zone backup/ 2>/dev/null

			eend ${rc} "Reverse map generation failed: ${rc}"
		)
	else
		ewarn "Not regenerating internal zones"
	fi
} # regenerateconfig

regenerateconfig || exit ${?}

set -u

# vi: set syntax=sh:
