#! /bin/sh

# openntpd has a '--with-cacert' option, which appears to define a preprocessor
# variable which is then never referenced, and the openntpd code makes a call
# which restores libretls' libressl compatibility to look for a CA file in
# /etc/ssl/cert.pem - so we need to make sure this file is available...

set -e

if ! [ -e /etc/ssl/cert.pem ]; then
	if [ -d /etc/ssl ] &&
			[ -w /etc/ssl ] &&
			touch -ac /etc/ssl/certs/ca-certificates.crt 2>/dev/null
	then
		ln -s certs/ca-certificates.crt /etc/ssl/cert.pem ||
			echo >&2 "FATAL: Linking 'certs/ca-certificates.crt' to" \
				"'cert.pem' in /etc/ssl failed: ${?}"
	else
		echo >&2 "FATAL: Unable to write to '/etc/ssl/cert.pem': ${?}"
	fi
fi
test -s /etc/ssl/cert.pem

# vi: set syntax=sh:
