#!/bin/sh

case "${1:-}" in
	eix|eix-[a-z]*|masked-packages|versionsort)
		export service_cmd="${1}"
		shift
		;;
	ebump|eclean|eclean-dist|eclean-pkg|ekeyword|enalyze|epkginfo|equery|eread|eshowkw|euse|imlate|merge-driver-ekeyword|revdep-rebuild|revdep-rebuild.sh|show|profile)
		export service_cmd="${1}"
		shift

		print '* Setting gentoolkit environment ...'

		if [ -e /etc/portage/repos.conf.host ]; then
			print "Mirroring host repos.conf to container ..."
			if [ -e /etc/portage/repos.conf ]; then
				if [ -d /etc/portage/repos.conf ]; then
					for f in /etc/portage/repos.conf/*; do
						umount -q "${f}" || :
					done
				fi
				umount -q /etc/portage/repos.conf || :
				rm -rf /etc/portage/repos.conf || :

				[ -e /etc/portage/repos.conf ] && mv /etc/portage/repos.conf /etc/portage/repos.conf.disabled
			fi
			if ! cp -a /etc/portage/repos.conf.host /etc/portage/repos.conf; then
				echo >&2 "FATAL: Can't copy host repos.conf: ${?}"
				exit 1
			fi
		fi

		# eselect always complains about the symlink...
		eselect profile set 1 >/dev/null 2>&1

		# This should already have been run by entrypoint.sh...
		#eselect python update --if-unset >/dev/null

		FEATURES="-ipc-sandbox -mount-sandbox -network-sandbox"
		export FEATURES

		if echo "${service_cmd}" | grep -Fqx -e show -e profile; then
			#ls -l /etc/portage/
			#echo

			eselect profile list
			eselect profile show
			echo "Current active python interpreter:"
			eselect python show

			exit 0
		fi
		;;
	*)
		print "Unrecognised command '${1:-}' (from '${*:-}'), will default to container CMD (currently 'versionsort')"
		;;
esac

# vi: set syntax=sh:
